### ISSUE TITLE
Unknown licenses for quite some java packages

### ISSUE THREAD

**Issue by jellelicht** [pmonks/tools-licenses#16]
## Dependencies with undetermined licenses:

I was using the `licenses` task and it failed to determine the license(s) for these dependencies:

  * io.opentracing/opentracing-api                                                                                                     
  * io.opentracing/opentracing-mock                                                                                                    
  * io.opentracing/opentracing-noop                                                                                                    
  * io.opentracing/opentracing-util                                                                                                    
  * javax.activation/activation                                                                                                        
  * javax.mail/mail                                                                                                                    
  * junit/junit                                                                                                                        
  * net.i2p.crypto/eddsa                                                                                                               
  * net.java.dev.jna/jna-platform                                                                                                      
  * net.jpountz.lz4/lz4                                                                                                                
  * org.activecomponents.jadex/jadex-distribution-minimal     
  * org.bouncycastle/bcpkix-jdk15on                                                                                                    
  * org.bouncycastle/bcprov-jdk15on                                                                                                    
  * org.bouncycastle/bcutil-jdk15on                                                                                                    
  * org.hamcrest/hamcrest-core                                                                                                         
  * org.nanohttpd/nanohttpd                                                                                                            
  * org.nanohttpd/nanohttpd-websocket                                                                                                  
  * org.ow2.asm/asm-analysis                                                                                                           
  * org.ow2.asm/asm-tree                                                                                                               
  * org.ow2.asm/asm-util                                                                                                               
  * org.tukaani/xz                                                                                                                     
  * org.xerial.snappy/snappy-java

**Comment by pmonks** [comment]
Thank you!  I'll figure out the licenses for these libraries and update the fallbacks list shortly.

**Comment by pmonks** [comment]
Fixed in rev a6fb4ef521cff0735c3f20e6d732d06536b4893d.
